wsk -i action delete linpack
wsk -i action delete matmul
wsk -i action delete float_operation 
wsk -i action delete chameleon 
wsk -i action delete video_processing 
wsk -i action delete image_processing 
wsk -i action delete model_training 
wsk -i action delete pyaes 
wsk -i action delete feature_extractor 
wsk -i action delete feature_reducer 
wsk -i action delete orchestrator 
wsk -i action delete get_job_status 
wsk -i action delete mapper 
wsk -i action delete reducer
wsk -i action delete driver 
wsk -i action delete cnn_image_classification 
wsk -i action delete ml_lr_prediction 
wsk -i action delete ml_video_face_detection 
wsk -i action delete rnn_generate_character_level